[PW-5492] - Add Fashioncheque, DE Cadeaukaart, update generic giftcard (savvy)
Adyen/adyen-shopware6 pull request #212
Opened 2021-09-24 15:10 UTC by Morerice

## Summary
This ticket will add the `Fashioncheque` and `DE Cadeaukaart` giftcards as separate payment methods on Shopware 6.
Also, update the current generic giftcard payment method from (savvy)

**Steps:**
1. Add Fashioncheque
2. Add DE Cadeaukaart
3. Update generic giftcard

2021-09-27 06:31 UTC, acampos1916 commented on src/PaymentMethods/DeCadeaukaartGiftCardPaymentMethod.php
> +        return 'DeCadeaukaart';
```suggestion
        return 'DeCadeaukaart giftcard';
```

2021-09-27 06:31 UTC, acampos1916 commented on src/PaymentMethods/FashionChequeGiftCardPaymentMethod.php
> +        return 'FashionCheque';
```suggestion
        return 'FashionCheque giftcard';
```

2021-09-27 06:32 UTC, acampos1916 requested changes
Looks good. Only added some extra shopper-facing description.

2021-09-27 11:26 UTC, acampos1916 approved these changes

2021-09-27 12:04 UTC, peterojo approved these changes

2021-09-27 15:07 UTC, peterojo approved these changes

2021-09-30 12:24 UTC, acampos1916 approved these changes

2021-09-30 12:25 UTC, merged