Release v3.15.0
Adyen/adyen-shopware6 pull request #478
Opened 2024-04-17 08:43 UTC by RokPopov

- #460 
- #476 
- #473 
- #466 
- #455 
- #458 
- #468 
- #427 
- #477

2024-05-14 14:45 UTC, candemiralp requested changes

2024-05-14 14:45 UTC, candemiralp commented on src/Resources/app/storefront/src/scss/base.scss
> +select{
This CSS selector is too broad and it affects all of the loaded `select` HTML elements. That needs to use id or class.

2024-05-14 14:48 UTC, candemiralp commented on src/Resources/app/storefront/src/scss/base.scss
> +select{
```suggestion
#giftcardDropdown {
```

2024-05-14 14:56 UTC, khushboo-singhvi submitted a review, later dismissed

2024-05-15 06:45 UTC, candemiralp approved these changes

2024-05-15 07:54 UTC, merged