[ECP-9277] Add Support for Billie payment method
Adyen/adyen-shopware6 pull request #517
Opened 2024-07-10 16:38 UTC by SushmitaThakur

2024-07-15 12:48 UTC, candemiralp commented on src/AdyenPaymentShopware6.php
>      private function updateTo3150(UpdateContext $updateContext): void
This payment method needs to be added with a separate function for the target version. For example, it's planned to be released as a part of v3.16.0, you should create a new update method in this class and call this method with a comparison. Version comparison examples can be found in the same class.

2024-07-15 12:49 UTC, candemiralp commented on src/Handlers/BilliePaymentMethodHandler.php
> +}
It's a best practice to add an single empty line to the end of the class.

2024-07-15 12:49 UTC, candemiralp commented on src/PaymentMethods/BilliePaymentMethod.php
> +}
It's a best practice to add an single empty line to the end of the class.

2024-07-15 12:51 UTC, candemiralp requested changes

2024-07-15 12:51 UTC, candemiralp commented on src/AdyenPaymentShopware6.php
> +            new PaymentMethods\BilliePaymentMethod()
This payment method needs to be added with a separate function for the target version. For example, it's planned to be released as a part of v3.16.0, you should create a new update method in this class and call this method with a comparison. Version comparison examples can be found in the same class.

2024-07-19 11:11 UTC, khushboo-singhvi submitted a review, later dismissed

2024-07-19 11:12 UTC, khushboo-singhvi commented on src/AdyenPaymentShopware6.php
Hey, won't it be V4.x.x

2024-07-19 11:13 UTC, khushboo-singhvi commented on src/AdyenPaymentShopware6.php
> +    private function updateTo3160(UpdateContext $updateContext): void
Same here?

2024-07-19 13:41 UTC, candemiralp approved these changes

2024-07-23 09:38 UTC, merged