Ecp 9437 v4
Adyen/adyen-shopware6 pull request #543
Opened 2024-09-03 07:04 UTC by khushboo-singhvi

## Summary

## Tested scenarios

**Fixed issue**:

2024-09-03 08:50 UTC, SushmitaThakur requested changes
Hey, the manual installation is not needed. Could you please update `docker compose` in place of `docker-compose -f .github/workflows/templates/docker-compose.playwright.yml run --rm playwright /e2e.sh' on line 60?

2024-09-05 06:36 UTC, candemiralp approved these changes

2024-09-05 08:58 UTC, SushmitaThakur approved these changes

2024-09-09 07:57 UTC, peterojo approved these changes

2024-09-09 12:42 UTC, candemiralp approved these changes

2024-09-09 13:09 UTC, merged